apiVersion: v1
kind: Pod
metadata:
  name: flask
  labels:
    role: myrole
spec:
  containers:
  - name: my-flask-test
    image: michaelouan26/simpple-flask-app:${BUILD_NUMBER}
    ports:
    - containerPort: 5000
